### PR TITLE
Alternative Error Handling

### PR DESCRIPTION
**Pull request by aljcalandra**
- Added an error class
- Made validation logic clearer in one case

### CODE REVIEW

**Comment by aljcalandra** [comment]
Is there anything that can be done for the failing tests or is this issue caused elsewhere?

**Comment by Wolfe1** [comment]
1. Thanks for the pull request long time no see ♥
2. That Edge test is just flakiness, not sure about the "generate_report" job either just thats just broken it looks like.
3. The chrome tests are actual "failures" caused by the code change (They passed today for a dependabot update from Robotframework). Since the error messages changed in your pull request, the expected values for those tests need to be modified to match.

**Comment by aljcalandra** [comment]
Oof just saw the response, I'll go through and fix that up when I get a chance

**Comment by aljcalandra** [comment]
The token used for the generate_report job does not have write permissions for issues/pullrequests so I think it'll fail until that gets updated.
Alternatively it might be worth looking into the replacing it with the summary action.

**Review by Wolfe1 — APPROVED** [review]

**Pull request merged**
